# Russell 1000 sector/industry classifications (auto-generated)
RUSSELL1000_OVERRIDES = {
    "A": ("Industrials", "Electrical Products"),
    "AA": ("Industrials", "Metal Fabrications"),
    "AAL": ("Consumer Discretionary", "Air Freight/Delivery Services"),
    "AAON": ("Industrials", "Industrial Machinery/Components"),
    "AAPL": ("Technology", "Consumer Electronics"),
    "ABBV": ("Health Care", "Other Pharmaceuticals"),
    "ABNB": ("Consumer Discretionary", "Hotels/Resorts"),
    "ABT": ("Health Care", "Medical/Dental Instruments"),
    "ACGL": ("Finance", "Property-Casualty Insurers"),
    "ACHC": ("Health Care", "Hospital/Nursing Management"),
    "ACI": ("Consumer Staples", "Food Chains"),
    "ACM": ("Consumer Discretionary", "Military/Government/Technical"),
    "ACN": ("Consumer Discretionary", "Business Services"),
    "ADBE": ("Technology", "Computer Software: Prepackaged Software"),
    "ADC": ("Real Estate", "Real Estate Investment Trusts"),
    "ADI": ("Technology", "Semiconductors"),
    "ADM": ("Consumer Defensive", "Farm Products"),
    "ADP": ("Consumer Discretionary", "Business Services"),
    "ADSK": ("Technology", "Computer Software: Prepackaged Software"),
    "ADT": ("Consumer Discretionary", "Diversified Commercial Services"),
    "AEE": ("Utilities", "Power Generation"),
    "AEP": ("Utilities", "Electric Utilities: Central"),
    "AES": ("Utilities", "Electric Utilities: Central"),
    "AFG": ("Finance", "Property-Casualty Insurers"),
    "AFL": ("Finance", "Accident &Health Insurance"),
    "AFRM": ("Technology", "EDP Services"),
    "AGCO": ("Industrials", "Industrial Machinery/Components"),
    "AGNC": ("Real Estate", "Real Estate Investment Trusts"),
    "AGO": ("Finance", "Property-Casualty Insurers"),
    "AIG": ("Finance", "Life Insurance"),
    "AIT": ("Industrials", "Industrial Machinery/Components"),
    "AIZ": ("Finance", "Specialty Insurers"),
    "AJG": ("Finance", "Specialty Insurers"),
    "AKAM": ("Consumer Discretionary", "Business Services"),
    "AL": ("Consumer Discretionary", "Diversified Commercial Services"),
    "ALB": ("Industrials", "Industrial Specialties"),
    "ALGM": ("Technology", "Semiconductors"),
    "ALGN": ("Health Care", "Industrial Specialties"),
    "ALK": ("Consumer Discretionary", "Air Freight/Delivery Services"),
    "ALL": ("Finance", "Property-Casualty Insurers"),
    "ALLE": ("Consumer Discretionary", "Diversified Commercial Services"),
    "ALLY": ("Finance", "Diversified Financial Services"),
    "ALNY": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "ALSN": ("Consumer Discretionary", "Auto Parts:O.E.M."),
    "AM": ("Utilities", "Natural Gas Distribution"),
    "AMAT": ("Technology", "Semiconductors"),
    "AMCR": ("Industrials", "Containers/Packaging"),
    "AMD": ("Technology", "Semiconductors"),
    "AME": ("Consumer Discretionary", "Metal Fabrications"),
    "AMG": ("Finance", "Investment Managers"),
    "AMGN": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "AMH": ("Real Estate", "Real Estate Investment Trusts"),
    "AMKR": ("Technology", "Semiconductors"),
    "AMP": ("Finance", "Investment Managers"),
    "AMT": ("Real Estate", "Real Estate Investment Trusts"),
    "AMZN": ("Consumer Discretionary", "Catalog/Specialty Distribution"),
    "AN": ("Consumer Discretionary", "Other Specialty Stores"),
    "ANET": ("Technology", "Computer peripheral equipment"),
    "AON": ("Finance", "Specialty Insurers"),
    "AOS": ("Industrials", "Industrial Machinery/Components"),
    "APA": ("Energy", "Oil & Gas Production"),
    "APD": ("Industrials", "Specialty Chemicals"),
    "APG": ("Consumer Discretionary", "Military/Government/Technical"),
    "APH": ("Technology", "Electrical Products"),
    "APLS": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "APO": ("Finance", "Investment Managers"),
    "APP": ("Technology", "EDP Services"),
    "APPF": ("Technology", "EDP Services"),
    "APTV": ("Consumer Discretionary", "Auto Parts:O.E.M."),
    "AR": ("Energy", "Oil & Gas Production"),
    "ARE": ("Real Estate", "Real Estate Investment Trusts"),
    "ARES": ("Finance", "Investment Managers"),
    "ARMK": ("Technology", "Interactive Media"),
    "ARW": ("Technology", "Electronic Components"),
    "ASH": ("Industrials", "Specialty Chemicals"),
    "ASTS": ("Technology", "Telecommunications Equipment"),  # P0-1: Telecom equipment is Technology
    "ATI": ("Industrials", "Steel/Iron Ore"),
    "ATO": ("Utilities", "Oil/Gas Transmission"),
    "ATR": ("Health Care", "Medical/Dental Instruments"),
    "AU": ("Basic Materials", "Precious Metals"),
    "AUR": ("Technology", "EDP Services"),
    "AVB": ("Real Estate", "Real Estate Investment Trusts"),
    "AVGO": ("Technology", "Semiconductors"),
    "AVT": ("Technology", "Electronic Components"),
    "AVTR": ("Industrials", "Industrial Specialties"),
    "AVY": ("Miscellaneous", "Office Equipment/Supplies/Services"),
    "AWK": ("Utilities", "Water Supply"),
    "AXON": ("Consumer Discretionary", "Military/Government/Technical"),
    "AXP": ("Finance", "Finance: Consumer Services"),
    "AXS": ("Finance", "Property-Casualty Insurers"),
    "AXTA": ("Consumer Discretionary", "Paints/Coatings"),
    "AYI": ("Consumer Discretionary", "Building Products"),
    "AZO": ("Consumer Cyclical", "Specialty Retail"),
    "BA": ("Industrials", "Aerospace"),
    "BAC": ("Finance", "Major Banks"),
    "BAH": ("Consumer Discretionary", "Professional Services"),
    "BALL": ("Industrials", "Containers/Packaging"),
    "BAM": ("Real Estate", "Building operators"),
    "BAX": ("Health Care", "Medical/Dental Instruments"),
    "BBWI": ("Miscellaneous", "Diversified Commercial Services"),
    "BBY": ("Consumer Discretionary", "Consumer Electronics/Video Chains"),
    "BC": ("Consumer Discretionary", "Homebuilding"),
    "BDX": ("Health Care", "Medical/Dental Instruments"),
    "BEN": ("Finance", "Investment Managers"),
    "BFAM": ("Consumer Discretionary", "Other Consumer Services"),
    "BG": ("Consumer Staples", "Farming/Seeds/Milling"),
    "BHF": ("Finance", "Life Insurance"),
    "BIIB": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "BILL": ("Technology", "Computer Software: Prepackaged Software"),
    "BIO": ("Industrials", "Biotechnology: Laboratory Analytical Instruments"),
    "BJ": ("Consumer Discretionary", "Department/Specialty Retail Stores"),
    "BK": ("Finance", "Investment Managers"),
    "BKNG": ("Consumer Discretionary", "Other Consumer Services"),
    "BKR": ("Energy", "Oilfield Services/Equipment"),
    "BLD": ("Industrials", "Engineering & Construction"),
    "BLDR": ("Consumer Discretionary", "RETAIL: Building Materials"),
    "BLK": ("Finance", "Investment Bankers/Brokers/Service"),
    "BMRN": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "BMY": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "BOKF": ("Finance", "Major Banks"),
    "BPOP": ("Finance", "Major Banks"),
    "BR": ("Consumer Discretionary", "Business Services"),
    "BRBR": ("Consumer Staples", "Beverages (Production/Distribution)"),
    "BRKR": ("Industrials", "Biotechnology: Laboratory Analytical Instruments"),
    "BRO": ("Finance", "Specialty Insurers"),
    "BROS": ("Consumer Discretionary", "Restaurants"),
    "BRX": ("Real Estate", "Real Estate Investment Trusts"),
    "BSX": ("Health Care", "Medical/Dental Instruments"),
    "BSY": ("Technology", "Retail: Computer Software & Peripheral Equipment"),
    "BURL": ("Consumer Discretionary", "Apparel"),
    "BWA": ("Consumer Discretionary", "Auto Parts:O.E.M."),
    "BX": ("Finance", "Investment Managers"),
    "BXP": ("Real Estate", "Real Estate Investment Trusts"),
    "BYD": ("Consumer Discretionary", "Movies/Entertainment"),
    "C": ("Finance", "Major Banks"),
    "CACC": ("Finance", "Finance: Consumer Services"),
    "CACI": ("Technology", "EDP Services"),
    "CAG": ("Consumer Staples", "Packaged Foods"),
    "CAH": ("Health Care", "Health Care Distribution"),  # Cardinal Health - drug distributor, low-margin
    "CAR": ("Consumer Discretionary", "Rental/Leasing Companies"),
    "CARR": ("Consumer Discretionary", "Wholesale Distributors"),
    "CASY": ("Miscellaneous", "Diversified Commercial Services"),
    "CAT": ("Industrials", "Construction/Ag Equipment/Trucks"),
    "CB": ("Finance", "Property-Casualty Insurers"),
    "CBRE": ("Finance", "Real Estate"),
    "CBSH": ("Finance", "Major Banks"),
    "CCCS": ("Technology", "Computer Software: Prepackaged Software"),
    "CCI": ("Real Estate", "Real Estate Investment Trusts"),
    "CCK": ("Industrials", "Containers/Packaging"),
    "CCL": ("Consumer Cyclical", "Travel Services"),
    "CDNS": ("Technology", "Computer Software: Prepackaged Software"),
    "CDW": ("Consumer Discretionary", "Catalog/Specialty Distribution"),
    "CE": ("Industrials", "Major Chemicals"),
    "CEG": ("Utilities", "Power Generation"),
    "CELH": ("Consumer Staples", "Beverages (Production/Distribution)"),
    "CERT": ("Technology", "Retail: Computer Software & Peripheral Equipment"),
    "CF": ("Industrials", "Agricultural Chemicals"),
    "CFG": ("Finance", "Major Banks"),
    "CFLT": ("Technology", "EDP Services"),
    "CFR": ("Finance", "Major Banks"),
    "CG": ("Finance", "Investment Managers"),
    "CGNX": ("Industrials", "Industrial Machinery/Components"),
    "CHD": ("Consumer Discretionary", "Package Goods/Cosmetics"),
    "CHDN": ("Consumer Discretionary", "Services-Misc. Amusement & Recreation"),
    "CHE": ("Health Care", "Medical/Nursing Services"),
    "CHH": ("Consumer Discretionary", "Hotels/Resorts"),
    "CHRD": ("Energy", "Oil & Gas Production"),
    "CHRW": ("Consumer Discretionary", "Oil Refining/Marketing"),
    "CHTR": ("Technology", "Telecommunications Equipment"),  # P0-1: Telecom equipment is Technology
    "CHWY": ("Consumer Discretionary", "Catalog/Specialty Distribution"),
    "CI": ("Health Care", "Managed Health Care"),  # Health insurance/managed care,
    "CIEN": ("Technology", "Telecommunications Equipment"),  # P0-1: Telecom equipment is Technology
    "CINF": ("Finance", "Property-Casualty Insurers"),
    "CIVI": ("Energy", "Oil & Gas Production"),
    "CL": ("Consumer Discretionary", "Package Goods/Cosmetics"),
    "CLVT": ("Technology", "EDP Services"),
    "CLX": ("Consumer Discretionary", "Specialty Chemicals"),
    "CMA": ("Finance", "Major Banks"),
    "CMCSA": ("Technology", "Telecommunications Equipment"),  # P0-1: Telecom equipment is Technology
    "CME": ("Finance", "Investment Bankers/Brokers/Service"),
    "CMG": ("Consumer Discretionary", "Restaurants"),
    "CMI": ("Industrials", "Construction/Ag Equipment/Trucks"),
    "CMS": ("Utilities", "Power Generation"),
    "CNA": ("Finance", "Property-Casualty Insurers"),
    "CNC": ("Health Care", "Managed Health Care"),  # Health insurance/managed care - use insurance valuation
    "CNM": ("Industrials", "Industrial Machinery/Components"),
    "CNP": ("Utilities", "Electric Utilities: Central"),
    "CNXC": ("Technology", "Computer Software: Prepackaged Software"),
    "COF": ("Finance", "Finance Companies"),
    "COHR": ("Industrials", "Industrial Machinery/Components"),
    "COIN": ("Technology", "EDP Services"),
    "COKE": ("Consumer Staples", "Beverages (Production/Distribution)"),
    "COLB": ("Finance", "Major Banks"),
    "COLD": ("Real Estate", "Real Estate Investment Trusts"),
    "COLM": ("Consumer Discretionary", "Apparel"),
    "COO": ("Health Care", "Ophthalmic Goods"),
    "COP": ("Energy", "Integrated oil Companies"),
    "CORT": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "COST": ("Consumer Discretionary", "Department/Specialty Retail Stores"),
    "COTY": ("Consumer Discretionary", "Package Goods/Cosmetics"),
    "CPB": ("Consumer Staples", "Packaged Foods"),
    "CPNG": ("Consumer Discretionary", "Durable Goods"),
    "CPRT": ("Consumer Discretionary", "Other Specialty Stores"),
    "CPT": ("Real Estate", "Real Estate Investment Trusts"),
    "CR": ("Industrials", "Office Equipment/Supplies/Services"),
    "CRH": ("Industrials", "Building Materials"),
    "CRL": ("Health Care", "Biotechnology: Commercial Physical & Biological Resarch"),
    "CRM": ("Technology", "Computer Software: Prepackaged Software"),
    "CROX": ("Consumer Discretionary", "Shoe Manufacturing"),
    "CRS": ("Industrials", "Steel/Iron Ore"),
    "CRUS": ("Technology", "Semiconductors"),
    "CRWD": ("Technology", "EDP Services"),
    "CSCO": ("Technology", "Computer Communications Equipment"),  # P0-1: Computer comms is Technology
    "CSGP": ("Finance", "Real Estate"),
    "CSX": ("Industrials", "Railroads"),
    "CTAS": ("Consumer Discretionary", "Business Services"),
    "CTRA": ("Energy", "Oil & Gas Production"),
    "CTSH": ("Technology", "EDP Services"),
    "CTVA": ("Industrials", "Major Chemicals"),
    "CUBE": ("Real Estate", "Real Estate Investment Trusts"),
    "CUZ": ("Real Estate", "Real Estate Investment Trusts"),
    "CVNA": ("Consumer Discretionary", "Other Specialty Stores"),
    "CVS": ("Health Care", "Managed Health Care"),
    "CVX": ("Energy", "Integrated oil Companies"),
    "CWEN": ("Utilities", "Electric Utilities: Central"),
    "CZR": ("Consumer Discretionary", "Hotels/Resorts"),
    "D": ("Utilities", "Electric Utilities: Central"),
    "DAL": ("Consumer Discretionary", "Air Freight/Delivery Services"),
    "DAR": ("Consumer Staples", "Farming/Seeds/Milling"),
    "DASH": ("Industrials", "Industrial Machinery/Components"),
    "DBX": ("Technology", "Computer Software: Prepackaged Software"),
    "DCI": ("Industrials", "Pollution Control Equipment"),
    "DD": ("Consumer Discretionary", "Wholesale Distributors"),
    "DDOG": ("Technology", "EDP Services"),
    "DDS": ("Consumer Discretionary", "Department/Specialty Retail Stores"),
    "DE": ("Industrials", "Industrial Machinery/Components"),
    "DECK": ("Consumer Discretionary", "Shoe Manufacturing"),
    "DELL": ("Technology", "Computer Manufacturing"),
    "DG": ("Consumer Discretionary", "Department/Specialty Retail Stores"),
    "DGX": ("Health Care", "Medical Specialities"),
    "DHI": ("Consumer Cyclical", "Residential Construction"),
    "DHR": ("Health Care", "Medical Specialities"),
    "DINO": ("Energy", "Integrated oil Companies"),
    "DIS": ("Consumer Discretionary", "Movies/Entertainment"),
    "DKNG": ("Consumer Discretionary", "Services-Misc. Amusement & Recreation"),
    "DKS": ("Consumer Discretionary", "Other Specialty Stores"),
    "DLB": ("Technology", "EDP Services"),
    "DLR": ("Real Estate", "Real Estate Investment Trusts"),
    "DLTR": ("Consumer Discretionary", "Department/Specialty Retail Stores"),
    "DOC": ("Real Estate", "Real Estate Investment Trusts"),
    "DOCS": ("Technology", "Retail: Computer Software & Peripheral Equipment"),
    "DOCU": ("Technology", "EDP Services"),
    "DOV": ("Industrials", "Industrial Machinery/Components"),
    "DOW": ("Industrials", "Industrial Specialties"),
    "DOX": ("Technology", "EDP Services"),
    "DPZ": ("Consumer Discretionary", "Food Distributors"),
    "DRI": ("Consumer Discretionary", "Restaurants"),
    "DRS": ("Industrials", "Military/Government/Technical"),
    "DT": ("Technology", "EDP Services"),
    "DTE": ("Utilities", "Electric Utilities: Central"),
    "DTM": ("Utilities", "Oil & Gas Production"),
    "DUK": ("Utilities", "Power Generation"),
    "DUOL": ("Technology", "Computer Software: Prepackaged Software"),
    "DV": ("Technology", "Computer Software: Prepackaged Software"),
    "DVA": ("Health Care", "Medical/Nursing Services"),
    "DVN": ("Energy", "Oil & Gas Production"),
    "DXC": ("Technology", "EDP Services"),
    "DXCM": ("Health Care", "Medical Specialities"),
    "EA": ("Consumer Discretionary", "Recreational Games/Products/Toys"),
    "EBAY": ("Consumer Discretionary", "Catalog/Specialty Distribution"),
    "ECL": ("Consumer Discretionary", "Package Goods/Cosmetics"),
    "ED": ("Utilities", "Power Generation"),
    "EEFT": ("Technology", "EDP Services"),
    "EFX": ("Finance", "Advertising"),
    "EGP": ("Real Estate", "Real Estate Investment Trusts"),
    "EHC": ("Health Care", "Medical Specialities"),
    "EIX": ("Utilities", "Electric Utilities: Central"),
    "EL": ("Consumer Discretionary", "Package Goods/Cosmetics"),
    "ELAN": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "ELF": ("Consumer Discretionary", "Package Goods/Cosmetics"),
    "ELS": ("Real Estate", "Real Estate Investment Trusts"),
    "ELV": ("Health Care", "Managed Health Care"),  # Health insurance/managed care,
    "EME": ("Industrials", "Engineering & Construction"),
    "EMN": ("Industrials", "Major Chemicals"),
    "EMR": ("Industrials", "Industrial Machinery/Components"),
    "ENPH": ("Technology", "Electrical Products"),
    "ENTG": ("Technology", "Semiconductors"),
    "EOG": ("Energy", "Oil & Gas Production"),
    "EPAM": ("Technology", "EDP Services"),
    "EPR": ("Real Estate", "Real Estate Investment Trusts"),
    "EQIX": ("Real Estate", "Real Estate Investment Trusts"),
    "EQR": ("Real Estate", "Real Estate Investment Trusts"),
    "EQT": ("Energy", "Oil & Gas Production"),
    "ES": ("Utilities", "Electric Utilities: Central"),
    "ESAB": ("Industrials", "Office Equipment/Supplies/Services"),
    "ESI": ("Industrials", "Industrial Specialties"),
    "ESS": ("Real Estate", "Real Estate Investment Trusts"),
    "ESTC": ("Technology", "Computer Software: Prepackaged Software"),
    "ETN": ("Industrials", "Industrial Machinery/Components"),
    "ETR": ("Utilities", "Electric Utilities: Central"),
    "ETSY": ("Consumer Discretionary", "Catalog/Specialty Distribution"),
    "EVR": ("Finance", "Investment Managers"),
    "EVRG": ("Utilities", "Power Generation"),
    "EW": ("Health Care", "Industrial Specialties"),
    "EWBC": ("Finance", "Commercial Banks"),
    "EXAS": ("Health Care", "Biotechnology: Commercial Physical & Biological Resarch"),
    "EXC": ("Utilities", "Power Generation"),
    "EXEL": ("Health Care", "Biotechnology: Commercial Physical & Biological Resarch"),
    "EXLS": ("Technology", "Retail: Computer Software & Peripheral Equipment"),
    "EXP": ("Industrials", "Building Materials"),
    "EXPD": ("Consumer Discretionary", "Oil Refining/Marketing"),
    "EXPE": ("Consumer Discretionary", "Other Consumer Services"),
    "EXR": ("Real Estate", "Real Estate Investment Trusts"),
    "F": ("Consumer Discretionary", "Auto Manufacturing"),
    "FAF": ("Finance", "Specialty Insurers"),
    "FANG": ("Energy", "Oil & Gas Production"),
    "FAST": ("Basic Materials", "Construction Materials"),
    "FCN": ("Consumer Discretionary", "Professional Services"),
    "FCNCA": ("Finance", "Major Banks"),
    "FCX": ("Basic Materials", "Metal Mining"),
    "FDX": ("Consumer Discretionary", "Air Freight/Delivery Services"),
    "FE": ("Utilities", "Electric Utilities: Central"),
    "FERG": ("Consumer Discretionary", "Industrial Machinery/Components"),
    "FFIV": ("Technology", "EDP Services"),
    "FHB": ("Finance", "Major Banks"),
    "FHN": ("Finance", "Major Banks"),
    "FICO": ("Technology", "Computer Software: Prepackaged Software"),
    "FIS": ("Consumer Discretionary", "Business Services"),
    "FITB": ("Finance", "Major Banks"),
    "FIVE": ("Consumer Discretionary", "Department/Specialty Retail Stores"),
    "FIX": ("Industrials", "Engineering & Construction"),
    "FLEX": ("Technology", "Electrical Products"),
    "FLO": ("Consumer Staples", "Farming/Seeds/Milling"),
    "FLS": ("Industrials", "Fluid Controls"),
    "FMC": ("Industrials", "Agricultural Chemicals"),
    "FNB": ("Finance", "Major Banks"),
    "FND": ("Consumer Discretionary", "RETAIL: Building Materials"),
    "FNF": ("Finance", "Specialty Insurers"),
    "FOUR": ("Technology", "EDP Services"),
    "FOX": ("Industrials", "Broadcasting"),
    "FOXA": ("Industrials", "Broadcasting"),
    "FR": ("Real Estate", "Real Estate Investment Trusts"),
    "FRHC": ("Finance", "Investment Bankers/Brokers/Service"),
    "FRT": ("Real Estate", "Real Estate Investment Trusts"),
    "FSLR": ("Technology", "Semiconductors"),
    "FTAI": ("Consumer Discretionary", "Diversified Commercial Services"),
    "FTI": ("Industrials", "Metal Fabrications"),
    "FTNT": ("Technology", "Security Systems Services"),
    "FTV": ("Industrials", "Industrial Machinery/Components"),
    "FWONA": ("Consumer Discretionary", "Movies/Entertainment"),
    "FWONK": ("Consumer Discretionary", "Movies/Entertainment"),
    "FYBR": ("Technology", "Telecommunications Equipment"),  # P0-1: Telecom equipment is Technology
    "G": ("Consumer Discretionary", "Professional Services"),
    "GD": ("Industrials", "Aerospace"),
    "GDDY": ("Technology", "EDP Services"),
    "GE": ("Technology", "Consumer Electronics/Appliances"),
    "GEN": ("Technology", "Computer Software: Prepackaged Software"),
    "GFS": ("Technology", "Semiconductors"),
    "GGG": ("Industrials", "Fluid Controls"),
    "GILD": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "GIS": ("Consumer Staples", "Food Chains"),
    "GL": ("Finance", "Life Insurance"),
    "GLOB": ("Consumer Discretionary", "Electronics Distribution"),
    "GLPI": ("Real Estate", "Real Estate Investment Trusts"),
    "GLW": ("Technology", "Industrial Machinery/Components"),
    "GM": ("Consumer Discretionary", "Auto Manufacturing"),
    "GME": ("Consumer Discretionary", "Electronics Distribution"),
    "GMED": ("Health Care", "Medical/Dental Instruments"),
    "GNRC": ("Consumer Discretionary", "Metal Fabrications"),
    "GNTX": ("Consumer Discretionary", "Auto Parts:O.E.M."),
    "GOOG": ("Technology", "Internet and Information Services"),
    "GOOGL": ("Technology", "Internet and Information Services"),
    "GOLD": ("Basic Materials", "Precious Metals"),  # Barrick Gold - gold mining
    "GPC": ("Consumer Discretionary", "Automotive Aftermarket"),
    "GPK": ("Basic Materials", "Paper"),
    "GPN": ("Consumer Discretionary", "Business Services"),
    "GRMN": ("Industrials", "Industrial Machinery/Components"),
    "GS": ("Finance", "Investment Bankers/Brokers/Service"),
    "GTES": ("Industrials", "Industrial Machinery/Components"),
    "GTLB": ("Technology", "EDP Services"),
    "GWRE": ("Technology", "Computer Software: Prepackaged Software"),
    "GWW": (
        "Consumer Discretionary",
        "Industrial Distribution",
    ),  # GWW is Grainger - industrial distributor, not telecom
    "H": ("Consumer Discretionary", "Hotels/Resorts"),
    "HAL": ("Energy", "Oil & Gas Production"),
    "HALO": ("Health Care", "Biotechnology: Biological Products (No Diagnostic Substances)"),
    "HAS": ("Consumer Discretionary", "Recreational Games/Products/Toys"),
    "HAYW": ("Technology", "Electronic Components"),
    "HBAN": ("Finance", "Major Banks"),
    "HCA": ("Health Care", "Hospital/Nursing Management"),
    "HD": ("Consumer Discretionary", "RETAIL: Building Materials"),
    "HEI": ("Industrials", "Military/Government/Technical"),
    "HIG": ("Finance", "Property-Casualty Insurers"),
    "HII": ("Industrials", "Metal Fabrications"),
    "HIW": ("Real Estate", "Real Estate Investment Trusts"),
    "HLI": ("Finance", "Investment Managers"),
    "HLNE": ("Finance", "Investment Managers"),
    "HLT": ("Consumer Discretionary", "Hotels/Resorts"),
    "HOG": ("Consumer Discretionary", "Motor Vehicles"),
    "HOLX": ("Health Care", "Medical Electronics"),
    "HON": ("Industrials", "Consumer Electronics/Appliances"),
    "HOOD": ("Technology", "Computer Software: Prepackaged Software"),
    "HPE": ("Technology", "Electronic Components"),
    "HPQ": ("Technology", "Computer Manufacturing"),
    "HR": ("Real Estate", "Real Estate Investment Trusts"),
    "HRB": ("Consumer Discretionary", "Other Consumer Services"),
    "HRL": ("Consumer Staples", "Meat/Poultry/Fish"),
    "HSIC": ("Health Care", "Medical Specialities"),
    "HST": ("Real Estate", "Real Estate Investment Trusts"),
    "HSY": ("Consumer Staples", "Specialty Foods"),
    "HUBB": ("Technology", "Industrial Machinery/Components"),
    "HUBS": ("Technology", "Computer Software: Prepackaged Software"),
    "HUM": ("Health Care", "Managed Health Care"),  # Health insurance/managed care,
    "HUN": ("Industrials", "Major Chemicals"),
    "HWM": ("Industrials", "Military/Government/Technical"),
    "HXL": ("Industrials", "Industrial Machinery/Components"),
    "IAC": ("Consumer Discretionary", "EDP Services"),
    "IBKR": ("Finance", "Investment Bankers/Brokers/Service"),
    "IBM": ("Technology", "EDP Services"),
    "ICE": ("Finance", "Investment Bankers/Brokers/Service"),
    "IDA": ("Utilities", "Electric Utilities: Central"),
    "IDXX": ("Health Care", "Biotechnology: In Vitro & In Vivo Diagnostic Substances"),
    "IEP": ("Finance", "Diversified Investments"),  # Icahn Enterprises - holding company
    "IEX": ("Industrials", "Fluid Controls"),
    "IFF": ("Industrials", "Major Chemicals"),
    "ILMN": ("Health Care", "Medical Specialities"),
    "INCY": ("Health Care", "Biotechnology: Commercial Physical & Biological Resarch"),
    "INFA": ("Technology", "EDP Services"),
    "INGR": ("Consumer Staples", "Farming/Seeds/Milling"),
    "INSM": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "INSP": ("Health Care", "Biotechnology: Electromedical & Electrotherapeutic Apparatus"),
    "INTC": ("Technology", "Semiconductors"),
    "INTU": ("Technology", "Computer Software: Prepackaged Software"),
    "INVH": ("Real Estate", "Real Estate Investment Trusts"),
    "IONS": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "IOT": ("Technology", "Retail: Computer Software & Peripheral Equipment"),
    "IP": ("Industrials", "Containers/Packaging"),
    "IPG": ("Consumer Discretionary", "Advertising"),
    "IPGP": ("Technology", "Semiconductors"),
    "IQV": ("Health Care", "Managed Health Care"),
    "IR": ("Industrials", "Industrial Machinery/Components"),
    "IRDM": ("Technology", "Telecommunications Equipment"),  # P0-1: Telecom equipment is Technology
    "IRM": ("Real Estate", "Real Estate Investment Trusts"),
    "ISRG": ("Health Care", "Medical/Dental Instruments"),
    "IT": ("Finance", "Diversified Commercial Services"),
    "ITT": ("Industrials", "Fluid Controls"),
    "ITW": ("Industrials", "Industrial Machinery/Components"),
    "IVZ": ("Finance", "Investment Managers"),
    "J": ("Industrials", "Oilfield Services/Equipment"),
    "JAZZ": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "JBHT": ("Industrials", "Trucking Freight/Courier Services"),
    "JBL": ("Technology", "Electrical Products"),
    "JCI": ("Industrials", "Industrial Machinery/Components"),
    "JEF": ("Finance", "Investment Bankers/Brokers/Service"),
    "JHG": ("Finance", "Investment Managers"),
    "JHX": ("Industrials", "Building Materials"),
    "JKHY": ("Technology", "Retail: Computer Software & Peripheral Equipment"),
    "JLL": ("Finance", "Real Estate"),
    "JNJ": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "JPM": ("Finance", "Major Banks"),
    "K": ("Consumer Staples", "Packaged Foods"),
    "KBR": ("Industrials", "Oilfield Services/Equipment"),
    "KD": ("Technology", "EDP Services"),
    "KDP": ("Consumer Staples", "Beverages (Production/Distribution)"),
    "KEX": ("Consumer Discretionary", "Marine Transportation"),
    "KEY": ("Finance", "Major Banks"),
    "KEYS": ("Industrials", "Industrial Machinery/Components"),
    "KHC": ("Consumer Staples", "Farming/Seeds/Milling"),
    "KIM": ("Real Estate", "Real Estate Investment Trusts"),
    "KKR": ("Finance", "Investment Managers"),
    "KLAC": ("Technology", "Electronic Components"),
    "KMB": ("Consumer Discretionary", "Paper"),
    "KMI": ("Utilities", "Natural Gas Distribution"),
    "KMPR": ("Finance", "Property-Casualty Insurers"),
    "KMX": ("Consumer Discretionary", "Other Specialty Stores"),
    "KNSL": ("Finance", "Property-Casualty Insurers"),
    "KNX": ("Industrials", "Trucking Freight/Courier Services"),
    "KO": ("Consumer Staples", "Beverages (Production/Distribution)"),
    "KR": ("Consumer Staples", "Food Chains"),
    "KRC": ("Real Estate", "Real Estate Investment Trusts"),
    "L": ("Finance", "Property-Casualty Insurers"),
    "LAD": ("Consumer Discretionary", "Other Specialty Stores"),
    "LAMR": ("Real Estate", "Real Estate Investment Trusts"),
    "LAZ": ("Finance", "Investment Managers"),
    "LBRDA": ("Technology", "Telecommunications Equipment"),  # P0-1: Telecom equipment is Technology
    "LBRDK": ("Technology", "Telecommunications Equipment"),  # P0-1: Telecom equipment is Technology
    "LBTYA": ("Telecommunications", "Cable & Other Pay Television Services"),
    "LBTYK": ("Telecommunications", "Cable & Other Pay Television Services"),
    "LCID": ("Consumer Discretionary", "Auto Manufacturing"),
    "LDOS": ("Technology", "EDP Services"),
    "LEA": ("Consumer Discretionary", "Auto Parts:O.E.M."),
    "LECO": ("Industrials", "Industrial Machinery/Components"),
    "LEN": ("Real Estate", "Building operators"),
    "LFUS": ("Technology", "Electronic Components"),
    "LH": ("Health Care", "Medical Specialities"),
    "LHX": ("Industrials", "Industrial Machinery/Components"),
    "LII": ("Industrials", "Industrial Machinery/Components"),
    "LIN": ("Industrials", "Major Chemicals"),
    "LITE": ("Technology", "Computer peripheral equipment"),
    "LKQ": ("Consumer Discretionary", "Automotive Aftermarket"),
    "LLY": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "LMT": ("Industrials", "Aerospace"),
    "LNC": ("Finance", "Life Insurance"),
    "LNT": ("Utilities", "Power Generation"),
    "LNW": ("Consumer Discretionary", "Movies/Entertainment"),
    "LOPE": ("Consumer Discretionary", "Service to the Health Industry"),
    "LOW": ("Consumer Discretionary", "RETAIL: Building Materials"),
    "LPLA": ("Finance", "Investment Bankers/Brokers/Service"),
    "LRCX": ("Technology", "Industrial Machinery/Components"),
    "LSCC": ("Technology", "Semiconductors"),
    "LSTR": ("Industrials", "Trucking Freight/Courier Services"),
    "LULU": ("Consumer Discretionary", "Department/Specialty Retail Stores"),
    "LUV": ("Consumer Discretionary", "Air Freight/Delivery Services"),
    "LVS": ("Consumer Discretionary", "Hotels/Resorts"),
    "LW": ("Consumer Staples", "Specialty Foods"),
    "LYB": ("Industrials", "Industrial Specialties"),
    "LYFT": ("Technology", "EDP Services"),
    "LYV": ("Consumer Discretionary", "Movies/Entertainment"),
    "M": ("Consumer Discretionary", "Department/Specialty Retail Stores"),
    "MA": ("Consumer Discretionary", "Business Services"),
    "MAA": ("Real Estate", "Real Estate Investment Trusts"),
    "MAN": ("Consumer Discretionary", "Professional Services"),
    "MANH": ("Technology", "Computer Software: Prepackaged Software"),
    "MAR": ("Consumer Discretionary", "Hotels/Resorts"),
    "MAS": ("Industrials", "Building Products"),
    "MASI": ("Health Care", "Medical/Dental Instruments"),
    "MAT": ("Consumer Discretionary", "Recreational Games/Products/Toys"),
    "MCD": ("Consumer Discretionary", "Restaurants"),
    "MCHP": ("Technology", "Semiconductors"),
    "MCK": ("Health Care", "Health Care Distribution"),  # McKesson - drug distributor, low-margin
    "MCO": ("Finance", "Advertising"),
    "MDB": ("Technology", "Retail: Computer Software & Peripheral Equipment"),
    "MDLZ": ("Consumer Staples", "Meat/Poultry/Fish"),
    "MDT": ("Health Care", "Biotechnology: Electromedical & Electrotherapeutic Apparatus"),
    "MDU": ("Industrials", "Consumer Electronics/Appliances"),
    "MEDP": ("Health Care", "Biotechnology: Commercial Physical & Biological Resarch"),
    "MET": ("Finance", "Life Insurance"),
    "META": ("Technology", "Internet and Information Services"),
    "MGM": ("Consumer Discretionary", "Hotels/Resorts"),
    "MHK": ("Consumer Discretionary", "Home Furnishings"),
    "MIDD": ("Industrials", "Diversified Manufacture"),
    "MKC": ("Consumer Staples", "Farming/Seeds/Milling"),
    "MKL": ("Finance", "Property-Casualty Insurers"),
    "MKSI": ("Industrials", "Industrial Machinery/Components"),
    "MKTX": ("Finance", "Investment Bankers/Brokers/Service"),
    "MLI": ("Industrials", "Metal Fabrications"),
    "MLM": ("Industrials", "Building Materials"),
    "MMC": ("Finance", "Specialty Insurers"),
    "MMM": ("Industrials", "Consumer Electronics/Appliances"),
    "MNST": ("Consumer Staples", "Beverages (Production/Distribution)"),
    "MO": ("Health Care", "Medicinal Chemicals and Botanical Products"),
    "MOH": ("Health Care", "Managed Health Care"),  # Health insurance/managed care,
    "MORN": ("Finance", "Advertising"),
    "MOS": ("Industrials", "Agricultural Chemicals"),
    "MP": ("Basic Materials", "Precious Metals"),
    "MPC": ("Energy", "Integrated oil Companies"),
    "MPW": ("Real Estate", "Real Estate Investment Trusts"),
    "MPWR": ("Technology", "Semiconductors"),
    "MRK": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "MRNA": ("Health Care", "Biotechnology: Biological Products (No Diagnostic Substances)"),
    "MRVL": ("Technology", "Semiconductors"),
    "MS": ("Finance", "Investment Bankers/Brokers/Service"),
    "MSA": ("Technology", "Security Systems Services"),
    "MSCI": ("Finance", "Advertising"),
    "MSFT": ("Technology", "Computer Software: Prepackaged Software"),
    "MSGS": ("Consumer Discretionary", "Hotels/Resorts"),
    "MSI": ("Technology", "Radio And Television Broadcasting And Communications Equipment"),
    "MSM": ("Industrials", "Industrial Machinery/Components"),
    "MSTR": ("Technology", "Computer Software: Prepackaged Software"),
    "MTB": ("Finance", "Major Banks"),
    "MTCH": ("Technology", "Computer Software: Programming Data Processing"),
    "MTD": ("Health Care", "Medical Specialities"),
    "MTDR": ("Energy", "Oil & Gas Production"),
    "MTG": ("Finance", "Property-Casualty Insurers"),
    "MTN": ("Consumer Discretionary", "Movies/Entertainment"),
    "MTSI": ("Technology", "Semiconductors"),
    "MTZ": ("Industrials", "Water Sewer Pipeline Comm & Power Line Construction"),
    "MU": ("Technology", "Semiconductors"),
    "MUSA": ("Utilities", "Natural Gas Distribution"),
    "NBIX": ("Health Care", "Biotechnology: Biological Products (No Diagnostic Substances)"),
    "NCLH": ("Consumer Discretionary", "Marine Transportation"),
    "NCNO": ("Technology", "Computer Software: Prepackaged Software"),
    "NDAQ": ("Finance", "Investment Bankers/Brokers/Service"),
    "NDSN": ("Industrials", "Industrial Machinery/Components"),
    "NEE": ("Utilities", "Electric Utilities: Central"),
    "NEM": ("Basic Materials", "Precious Metals"),
    "NET": ("Technology", "EDP Services"),
    "NEU": ("Industrials", "Major Chemicals"),
    "NFG": ("Energy", "Oil & Gas Production"),
    "NFLX": ("Consumer Discretionary", "Consumer Electronics/Video Chains"),
    "NI": ("Utilities", "Power Generation"),
    "NIQ": ("Finance", "Finance/Investors Services"),
    "NKE": ("Consumer Discretionary", "Shoe Manufacturing"),
    "NLY": ("Real Estate", "Real Estate Investment Trusts"),
    "NNN": ("Real Estate", "Real Estate Investment Trusts"),
    "NOC": ("Technology", "Security Systems Services"),
    "NOV": ("Industrials", "Metal Fabrications"),
    "NOW": ("Technology", "Computer Software: Prepackaged Software"),
    "NRG": ("Utilities", "Electric Utilities: Central"),
    "NSA": ("Real Estate", "Real Estate Investment Trusts"),
    "NSC": ("Industrials", "Railroads"),
    "NTAP": ("Technology", "Electronic Components"),
    "NTNX": ("Technology", "EDP Services"),
    "NTRA": ("Health Care", "Medical Specialities"),
    "NTRS": ("Finance", "Trusts Except Educational Religious and Charitable"),
    "NU": ("Finance", "Finance: Consumer Services"),
    "NUE": ("Industrials", "Steel/Iron Ore"),
    "NVDA": ("Technology", "Semiconductors"),  # P0-1: Normalized sector to Technology
    "NVR": ("Consumer Discretionary", "Homebuilding"),
    "NVST": ("Health Care", "Medical/Dental Instruments"),
    "NVT": ("Technology", "Electrical Products"),
    "NWL": ("Industrials", "Plastic Products"),
    "NWS": ("Consumer Discretionary", "Movies/Entertainment"),
    "NWSA": ("Consumer Discretionary", "Movies/Entertainment"),
    "NXST": ("Consumer Discretionary", "Movies/Entertainment"),
    "NYT": ("Consumer Discretionary", "Newspapers/Magazines"),
    "O": ("Real Estate", "Real Estate Investment Trusts"),
    "ODFL": ("Industrials", "Trucking Freight/Courier Services"),
    "OGE": ("Utilities", "Electric Utilities: Central"),
    "OGN": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "OHI": ("Real Estate", "Real Estate Investment Trusts"),
    "OKE": ("Utilities", "Oil & Gas Production"),
    "OKTA": ("Technology", "EDP Services"),
    "OLED": ("Technology", "Industrial Machinery/Components"),
    "OLLI": ("Consumer Discretionary", "Department/Specialty Retail Stores"),
    "OLN": ("Industrials", "Industrial Specialties"),
    "OMC": ("Consumer Discretionary", "Advertising"),
    "OMF": ("Finance", "Finance: Consumer Services"),
    "ON": ("Technology", "Semiconductors"),
    "ONON": ("Consumer Discretionary", "Shoe Manufacturing"),
    "ONTO": ("Technology", "Semiconductors"),
    "ORCL": ("Technology", "Computer Software: Prepackaged Software"),
    "ORI": ("Finance", "Specialty Insurers"),
    "ORLY": ("Consumer Discretionary", "Auto & Home Supply Stores"),
    "OSK": ("Consumer Discretionary", "Auto Manufacturing"),
    "OTIS": ("Industrials", "Specialty Industrial Machinery"),
    "OVV": ("Energy", "Oil & Gas Production"),
    "OWL": ("Finance", "Investment Managers"),
    "OXY": ("Energy", "Oil & Gas Production"),
    "OZK": ("Finance", "Major Banks"),
    "PAG": ("Consumer Discretionary", "Other Specialty Stores"),
    "PANW": ("Technology", "EDP Services"),
    "PATH": ("Technology", "Computer Software: Prepackaged Software"),
    "PAYC": ("Technology", "Computer Software: Prepackaged Software"),
    "PAYX": ("Consumer Discretionary", "Business Services"),
    "PB": ("Finance", "Major Banks"),
    "PCAR": ("Industrials", "Construction/Ag Equipment/Trucks"),
    "PCG": ("Utilities", "Power Generation"),
    "PCOR": ("Technology", "EDP Services"),
    "PCTY": ("Technology", "Computer Software: Prepackaged Software"),
    "PEG": ("Utilities", "Power Generation"),
    "PEGA": ("Technology", "EDP Services"),
    "PEN": ("Health Care", "Medical/Dental Instruments"),
    "PENN": ("Consumer Discretionary", "Movies/Entertainment"),
    "PEP": ("Consumer Staples", "Beverages (Production/Distribution)"),
    "PFE": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "PFG": ("Finance", "Investment Managers"),
    "PFGC": ("Consumer Discretionary", "Food Distributors"),
    "PG": ("Consumer Discretionary", "Package Goods/Cosmetics"),
    "PGR": ("Finance", "Property-Casualty Insurers"),
    "PH": ("Industrials", "Office Equipment/Supplies/Services"),
    "PHM": ("Consumer Cyclical", "Residential Construction"),
    "PINS": ("Technology", "Interactive Media"),
    "PK": ("Real Estate", "Real Estate Investment Trusts"),
    "PKG": ("Basic Materials", "Paper"),
    "PLD": ("Real Estate", "Real Estate Investment Trusts"),
    "PLNT": ("Consumer Discretionary", "Other Consumer Services"),
    "PLTR": ("Technology", "Retail: Computer Software & Peripheral Equipment"),
    "PM": ("Health Care", "Medicinal Chemicals and Botanical Products"),
    "PNC": ("Finance", "Major Banks"),
    "PNFP": ("Finance", "Major Banks"),
    "PNR": ("Industrials", "Fluid Controls"),
    "PNW": ("Utilities", "Electric Utilities: Central"),
    "PODD": ("Health Care", "Medical/Dental Instruments"),
    "POOL": ("Industrials", "Industrial Machinery/Components"),
    "POST": ("Consumer Discretionary", "Food Distributors"),
    "PPC": ("Consumer Staples", "Meat/Poultry/Fish"),
    "PPG": ("Consumer Discretionary", "Paints/Coatings"),
    "PPL": ("Utilities", "Electric Utilities: Central"),
    "PR": ("Energy", "Oil & Gas Production"),
    "PRGO": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "PRI": ("Finance", "Life Insurance"),
    "PRU": ("Finance", "Life Insurance"),
    "PSA": ("Real Estate", "Real Estate Investment Trusts"),
    "PSN": ("Industrials", "Industrial Machinery/Components"),
    "PSTG": ("Technology", "Electronic Components"),
    "PSX": ("Energy", "Integrated oil Companies"),
    "PTC": ("Technology", "Computer Software: Prepackaged Software"),
    "PWR": ("Industrials", "Engineering & Construction"),
    "PYPL": ("Consumer Discretionary", "Business Services"),
    "QCOM": ("Technology", "Computer peripheral equipment"),
    "QGEN": ("Health Care", "Biotechnology: Biological Products (No Diagnostic Substances)"),
    "QRVO": ("Industrials", "Industrial Machinery/Components"),
    "QS": ("Consumer Discretionary", "Auto Parts:O.E.M."),
    "R": ("Consumer Discretionary", "Rental/Leasing Companies"),
    "RARE": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "RBC": ("Industrials", "Metal Fabrications"),
    "RBLX": ("Technology", "EDP Services"),
    "RCL": ("Consumer Discretionary", "Hotels/Resorts"),
    "REG": ("Real Estate", "Real Estate Investment Trusts"),
    "REGN": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "REXR": ("Real Estate", "Real Estate Investment Trusts"),
    "REYN": ("Industrials", "Office Equipment/Supplies/Services"),
    "RF": ("Finance", "Major Banks"),
    "RGA": ("Finance", "Life Insurance"),
    "RGEN": ("Health Care", "Medical/Dental Instruments"),
    "RGLD": ("Industrials", "Consumer Electronics/Appliances"),
    "RH": ("Consumer Discretionary", "Other Specialty Stores"),
    "RHI": ("Consumer Discretionary", "Diversified Commercial Services"),
    "RITM": ("Real Estate", "Real Estate Investment Trusts"),
    "RIVN": ("Consumer Discretionary", "Auto Manufacturing"),
    "RJF": ("Finance", "Investment Bankers/Brokers/Service"),
    "RKLB": ("Industrials", "Aerospace"),
    "RKT": ("Finance", "Finance: Consumer Services"),
    "RL": ("Consumer Discretionary", "Apparel"),
    "RLI": ("Finance", "Property-Casualty Insurers"),
    "RMD": ("Health Care", "Medical/Dental Instruments"),
    "RNG": ("Technology", "EDP Services"),
    "RNR": ("Finance", "Property-Casualty Insurers"),
    "ROIV": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "ROK": ("Industrials", "Industrial Machinery/Components"),
    "ROKU": ("Telecommunications", "Cable & Other Pay Television Services"),
    "ROL": ("Consumer Discretionary", "Industrial Specialties"),
    "ROP": ("Industrials", "Office Equipment/Supplies/Services"),
    "ROST": ("Consumer Discretionary", "Clothing/Shoe/Accessory Stores"),
    "RPM": ("Consumer Discretionary", "Paints/Coatings"),
    "RPRX": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "RRC": ("Energy", "Oil & Gas Production"),
    "RRX": ("Consumer Discretionary", "Metal Fabrications"),
    "RS": ("Industrials", "Steel/Iron Ore"),
    "RSG": ("Utilities", "Environmental Services"),
    "RTX": ("Industrials", "Military/Government/Technical"),
    "RVMD": ("Health Care", "Medicinal Chemicals and Botanical Products"),
    "RYN": ("Real Estate", "Real Estate Investment Trusts"),
    "S": ("Technology", "EDP Services"),
    "SAIA": ("Industrials", "Trucking Freight/Courier Services"),
    "SAIC": ("Technology", "EDP Services"),
    "SAM": ("Consumer Staples", "Beverages (Production/Distribution)"),
    "SBAC": ("Real Estate", "Real Estate Investment Trusts"),
    "SBUX": ("Consumer Staples", "Specialty Foods"),
    "SCCO": ("Basic Materials", "Metal Mining"),
    "SCHW": ("Finance", "Investment Bankers/Brokers/Service"),
    "SCI": ("Consumer Discretionary", "Other Consumer Services"),
    "SEE": ("Industrials", "Containers/Packaging"),
    "SEIC": ("Finance", "Investment Bankers/Brokers/Service"),
    "SF": ("Finance", "Investment Bankers/Brokers/Service"),
    "SFM": ("Consumer Discretionary", "Specialty Foods"),
    "SHC": ("Health Care", "Medical Specialities"),
    "SHW": ("Consumer Discretionary", "Paints/Coatings"),
    "SIRI": ("Consumer Discretionary", "Movies/Entertainment"),
    "SJM": ("Consumer Staples", "Packaged Foods"),
    "SLB": ("Energy", "Oilfield Services/Equipment"),
    "SLGN": ("Industrials", "Containers/Packaging"),
    "SLM": ("Finance", "Finance: Consumer Services"),
    "SMCI": ("Technology", "Computer Manufacturing"),
    "SMG": ("Industrials", "Agricultural Chemicals"),
    "SMMT": ("Health Care", "Medicinal Chemicals and Botanical Products"),
    "SNA": ("Consumer Discretionary", "Diversified Manufacture"),
    "SNDR": ("Industrials", "Trucking Freight/Courier Services"),
    "SNOW": ("Technology", "Computer Software: Prepackaged Software"),
    "SNPS": ("Technology", "EDP Services"),
    "SNV": ("Finance", "Major Banks"),
    "SNX": ("Consumer Discretionary", "Electronics Distribution"),
    "SO": ("Utilities", "Power Generation"),
    "SOFI": ("Finance", "Diversified Financial Services"),
    "SON": ("Industrials", "Containers/Packaging"),
    "SPG": ("Real Estate", "Real Estate Investment Trusts"),
    "SPGI": ("Finance", "Advertising"),
    "SPOT": ("Consumer Discretionary", "Broadcasting"),
    "SPR": ("Industrials", "Military/Government/Technical"),
    "SRE": ("Utilities", "Oil/Gas Transmission"),
    "SRPT": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "SSB": ("Finance", "Major Banks"),
    "SSNC": ("Technology", "Computer Software: Prepackaged Software"),
    "ST": ("Industrials", "Industrial Machinery/Components"),
    "STAG": ("Real Estate", "Real Estate Investment Trusts"),
    "STE": ("Health Care", "Industrial Specialties"),
    "STLD": ("Industrials", "Steel/Iron Ore"),
    "STT": ("Finance", "Investment Managers"),
    "STWD": ("Real Estate", "Real Estate Investment Trusts"),
    "STZ": ("Consumer Staples", "Beverages (Production/Distribution)"),
    "SUI": ("Real Estate", "Real Estate Investment Trusts"),
    "SWK": ("Consumer Discretionary", "Diversified Manufacture"),
    "SWKS": ("Technology", "Semiconductors"),
    "SYF": ("Finance", "Diversified Financial Services"),
    "SYK": ("Health Care", "Medical/Dental Instruments"),
    "SYY": ("Consumer Discretionary", "Food Distributors"),
    "T": ("Technology", "Telecommunications Equipment"),  # P0-1: Telecom equipment is Technology
    "TAP": ("Consumer Staples", "Beverages (Production/Distribution)"),
    "TDC": ("Technology", "EDP Services"),
    "TDG": ("Industrials", "Military/Government/Technical"),
    "TDY": ("Industrials", "Industrial Machinery/Components"),
    "TEAM": ("Technology", "EDP Services"),
    "TECH": ("Health Care", "Biotechnology: Biological Products (No Diagnostic Substances)"),
    "TER": ("Industrials", "Electrical Products"),
    "TFC": ("Finance", "Major Banks"),
    "TFSL": ("Finance", "Savings Institutions"),
    "TFX": ("Health Care", "Medical/Dental Instruments"),
    "TGT": ("Consumer Discretionary", "Department/Specialty Retail Stores"),
    "THC": ("Health Care", "Hospital/Nursing Management"),
    "THG": ("Finance", "Property-Casualty Insurers"),
    "THO": ("Industrials", "Homebuilding"),
    "TIGO": ("Telecommunications", "Telecommunications Equipment"),
    "TJX": ("Consumer Discretionary", "Department/Specialty Retail Stores"),
    "TKR": ("Industrials", "Metal Fabrications"),
    "TMO": ("Industrials", "Biotechnology: Laboratory Analytical Instruments"),
    "TMUS": ("Telecommunications", "Telecommunications Equipment"),
    "TNL": ("Consumer Discretionary", "Hotels/Resorts"),
    "TOL": ("Consumer Discretionary", "Homebuilding"),
    "TOST": ("Technology", "EDP Services"),
    "TPG": ("Finance", "Trusts Except Educational Religious and Charitable"),
    "TPL": ("Energy", "Oil & Gas Production"),
    "TPR": ("Consumer Discretionary", "Apparel"),
    "TRGP": ("Utilities", "Natural Gas Distribution"),
    "TRMB": ("Industrials", "Industrial Machinery/Components"),
    "TROW": ("Finance", "Investment Managers"),
    "TRU": ("Finance", "Advertising"),
    "TRV": ("Finance", "Property-Casualty Insurers"),
    "TSCO": ("Consumer Discretionary", "Other Specialty Stores"),
    "TSLA": ("Technology", "SemiConductors"),
    "TSN": ("Consumer Staples", "Meat/Poultry/Fish"),
    "TT": ("Industrials", "Auto Parts:O.E.M."),
    "TTC": ("Consumer Discretionary", "Tools/Hardware"),
    "TTD": ("Technology", "EDP Services"),
    "TTEK": ("Consumer Discretionary", "Military/Government/Technical"),
    "TTWO": ("Technology", "Computer Software: Prepackaged Software"),
    "TW": ("Finance", "Investment Bankers/Brokers/Service"),
    "TWLO": ("Industrials", "Industrial Machinery/Components"),
    "TXN": ("Technology", "Semiconductors"),
    "TXRH": ("Consumer Discretionary", "Restaurants"),
    "TXT": ("Industrials", "Aerospace"),
    "TYL": ("Technology", "Computer Software: Prepackaged Software"),
    "U": ("Technology", "Retail: Computer Software & Peripheral Equipment"),
    "UA": ("Consumer Discretionary", "Apparel"),
    "UAA": ("Consumer Discretionary", "Apparel"),
    "UAL": ("Consumer Discretionary", "Air Freight/Delivery Services"),
    "UBER": ("Technology", "EDP Services"),
    "UDR": ("Real Estate", "Real Estate Investment Trusts"),
    "UGI": ("Utilities", "Natural Gas Distribution"),
    "UHAL": ("Consumer Discretionary", "Rental/Leasing Companies"),
    "UHALB": ("Consumer Discretionary", "Rental/Leasing Companies"),
    "UHS": ("Health Care", "Hospital/Nursing Management"),
    "UI": ("Technology", "Radio And Television Broadcasting And Communications Equipment"),
    "ULTA": ("Consumer Cyclical", "Specialty Retail"),
    "UNH": ("Health Care", "Managed Health Care"),  # Health insurance/managed care,
    "UNM": ("Finance", "Accident &Health Insurance"),
    "UNP": ("Industrials", "Railroads"),
    "UPS": ("Consumer Discretionary", "Air Freight/Delivery Services"),
    "URI": ("Consumer Discretionary", "Diversified Commercial Services"),
    "USB": ("Finance", "Major Banks"),
    "USFD": ("Consumer Discretionary", "Food Distributors"),
    "UTHR": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "UWMC": ("Finance", "Finance: Consumer Services"),
    "V": ("Financial Services", "Credit Services"),
    "VEEV": ("Health Care", "Managed Health Care"),
    "VFC": ("Consumer Discretionary", "Apparel"),
    "VICI": ("Real Estate", "Real Estate Investment Trusts"),
    "VIRT": ("Finance", "Investment Bankers/Brokers/Service"),
    "VKTX": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "VLO": ("Energy", "Integrated oil Companies"),
    "VMC": ("Basic Materials", "Building Materials"),
    "VMI": ("Industrials", "Construction/Ag Equipment/Trucks"),
    "VNO": ("Real Estate", "Real Estate Investment Trusts"),
    "VNOM": ("Energy", "Oil & Gas Production"),
    "VNT": ("Industrials", "Industrial Machinery/Components"),
    "VOYA": ("Finance", "Investment Managers"),
    "VRSK": ("Consumer Discretionary", "Business Services"),
    "VRSN": ("Technology", "EDP Services"),
    "VRT": ("Consumer Discretionary", "Electrical Products"),
    "VRTX": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
    "VST": ("Utilities", "Power Generation"),
    "VTR": ("Real Estate", "Real Estate Investment Trusts"),
    "VTRS": ("Health Care", "Medicinal Chemicals and Botanical Products"),
    "VVV": ("Industrials", "Automotive Aftermarket"),
    "W": ("Consumer Discretionary", "Catalog/Specialty Distribution"),
    "WAB": ("Industrials", "Railroads"),
    "WAL": ("Finance", "Major Banks"),
    "WAT": ("Health Care", "Medical Specialities"),
    "WBD": ("Telecommunications", "Cable & Other Pay Television Services"),
    "WBS": ("Finance", "Major Banks"),
    "WCC": ("Technology", "Telecommunications Equipment"),  # P0-1: Telecom equipment is Technology
    "WDAY": ("Technology", "Computer Software: Prepackaged Software"),
    "WDC": ("Technology", "Electronic Components"),
    "WEC": ("Utilities", "Power Generation"),
    "WELL": ("Real Estate", "Real Estate Investment Trusts"),
    "WEN": ("Consumer Discretionary", "Restaurants"),
    "WEX": ("Technology", "EDP Services"),
    "WFC": ("Finance", "Major Banks"),
    "WFRD": ("Industrials", "Metal Fabrications"),
    "WH": ("Consumer Discretionary", "Hotels/Resorts"),
    "WHR": ("Consumer Discretionary", "Consumer Electronics/Appliances"),
    "WING": ("Consumer Discretionary", "Restaurants"),
    "WLK": ("Industrials", "Major Chemicals"),
    "WM": ("Utilities", "Environmental Services"),
    "WMB": ("Utilities", "Natural Gas Distribution"),
    "WMS": ("Industrials", "Building Products"),
    "WMT": ("Consumer Discretionary", "Department/Specialty Retail Stores"),
    "WPC": ("Real Estate", "Real Estate Investment Trusts"),
    "WRB": ("Finance", "Property-Casualty Insurers"),
    "WSC": ("Consumer Discretionary", "Diversified Commercial Services"),
    "WSM": ("Consumer Discretionary", "Other Specialty Stores"),
    "WSO": ("Consumer Discretionary", "Wholesale Distributors"),
    "WST": ("Health Care", "Medical/Dental Instruments"),
    "WTFC": ("Finance", "Major Banks"),
    "WTM": ("Finance", "Property-Casualty Insurers"),
    "WTRG": ("Utilities", "Water Supply"),
    "WTW": ("Finance", "Specialty Insurers"),
    "WU": ("Consumer Discretionary", "Business Services"),
    "WWD": ("Industrials", "Military/Government/Technical"),
    "WY": ("Real Estate", "Real Estate Investment Trusts"),
    "WYNN": ("Consumer Discretionary", "Hotels/Resorts"),
    "XEL": ("Utilities", "Power Generation"),
    "XOM": ("Energy", "Oil & Gas Production"),
    "XP": ("Finance", "Investment Bankers/Brokers/Service"),
    "XPO": ("Consumer Discretionary", "Oil Refining/Marketing"),
    "XRAY": ("Health Care", "Medical/Dental Instruments"),
    "XYL": ("Industrials", "Fluid Controls"),
    "YETI": ("Consumer Discretionary", "Movies/Entertainment"),
    "YUM": ("Consumer Discretionary", "Restaurants"),
    "Z": ("Consumer Discretionary", "Business Services"),
    "ZBH": ("Health Care", "Industrial Specialties"),
    "ZBRA": ("Technology", "Computer peripheral equipment"),
    "ZG": ("Consumer Discretionary", "Business Services"),
    "ZION": ("Finance", "Major Banks"),
    "ZM": ("Technology", "Computer Software: Prepackaged Software"),
    "ZS": ("Technology", "EDP Services"),
    "ZTS": ("Health Care", "Biotechnology: Pharmaceutical Preparations"),
}
