import gzip
import json
from pathlib import Path

import pytest

from investigator.infrastructure.cache.cache_types import CacheType
from investigator.infrastructure.cache.file_cache_handler import FileCacheStorageHandler


@pytest.fixture
def cache_root(tmp_path: Path) -> Path:
    return tmp_path


def _build_handler(cache_type: CacheType, root: Path) -> FileCacheStorageHandler:
    handler_root = root / cache_type.value
    return FileCacheStorageHandler(cache_type=cache_type, base_path=handler_root, priority=10)


def test_llm_response_set_get_delete_cycle(cache_root: Path) -> None:
    handler = _build_handler(CacheType.LLM_RESPONSE, cache_root)
    key = {
        "symbol": "TEST",
        "llm_type": "synthesis_quarterly",
        "fiscal_year": "2025",
        "fiscal_period": "Q1",
        "period": "2025-Q1",
        "form_type": "10-Q",
    }
    value = {
        "prompt": "Summarise TEST",
        "response": {"symbol": "TEST", "score": 8.1},
        "metadata": {"symbol": "TEST"},
    }

    assert not handler.exists(key)
    assert handler.get(key) is None

    assert handler.set(key, value) is True
    assert handler.exists(key)

    stored = handler.get(key)
    assert stored is not None
    assert stored["prompt"] == value["prompt"]
    assert stored["response"]["symbol"] == "TEST"
    assert stored["response"]["score"] == pytest.approx(8.1)
    # Metadata is generated by the handler and contains audit fields; ensure core attributes are present.
    metadata = stored.get("metadata")
    assert metadata and metadata.get("cache_type") == CacheType.LLM_RESPONSE.value
    assert metadata.get("cache_key", {}).get("symbol") == "TEST"

    normalised_key = handler._normalize_key(key)  # pylint: disable=protected-access
    file_path = handler._get_file_path(normalised_key)  # pylint: disable=protected-access
    prompt_path = file_path.parent / f"prompt_{file_path.stem.replace('.json', '')}.txt.gz"
    response_path = file_path.parent / f"llmresponse_{file_path.stem.replace('.json', '')}.json.gz"

    assert prompt_path.exists()
    assert response_path.exists()

    with gzip.open(prompt_path, "rt", encoding="utf-8") as fh:
        assert fh.read() == value["prompt"]

    with gzip.open(response_path, "rt", encoding="utf-8") as fh:
        on_disk = json.load(fh)
    assert on_disk["response"]["symbol"] == "TEST"

    assert handler.delete(key) is True
    assert not handler.exists(key)
    assert handler.get(key) is None


@pytest.mark.parametrize(
    "key",
    [
        ("TEST", "synthesis", "2025-Q1", "10-Q", "2025", "Q1"),
        {"symbol": "TEST", "llm_type": "synthesis", "period": "2025-Q1", "form_type": "10-Q"},
    ],
)
def test_key_normalisation_supports_tuple_and_dict(cache_root: Path, key) -> None:
    handler = _build_handler(CacheType.LLM_RESPONSE, cache_root)
    normalised = handler._normalize_key(key)  # pylint: disable=protected-access
    assert normalised["symbol"] == "TEST"
    assert normalised["llm_type"].startswith("synthesis")


def test_clear_all_removes_cache_content(cache_root: Path) -> None:
    handler = _build_handler(CacheType.COMPANY_FACTS, cache_root)
    key = {"symbol": "TEST", "cik": "0000123456"}
    value = {
        "symbol": "TEST",
        "cik": "0000123456",
        "companyfacts": {"facts": {"us-gaap": {}}},
    }

    assert handler.set(key, value)

    cache_dir = handler.base_path
    assert any(cache_dir.rglob("*.json.gz"))

    assert handler.clear_all() is True
    assert not any(cache_dir.rglob("*.json.gz"))
